<?php

// scoper-autoload.php @generated by PhpScoper

$loader = (static function () {
    // Backup the autoloaded Composer files
    $existingComposerAutoloadFiles = isset($GLOBALS['__composer_autoload_files']) ? $GLOBALS['__composer_autoload_files'] : [];

    $loader = require_once __DIR__.'/autoload.php';
    // Ensure InstalledVersions is available
    $installedVersionsPath = __DIR__.'/composer/InstalledVersions.php';
    if (file_exists($installedVersionsPath)) require_once $installedVersionsPath;

    // Restore the backup and ensure the excluded files are properly marked as loaded
    $GLOBALS['__composer_autoload_files'] = \array_merge(
        $existingComposerAutoloadFiles,
        \array_fill_keys(['8e34e7a45845df1c24f360ac7179edb2'], true)
    );

    return $loader;
})();

// Class aliases. For more information see:
// https://github.com/humbug/php-scoper/blob/master/docs/further-reading.md#class-aliases
if (!function_exists('humbug_phpscoper_expose_class')) {
    function humbug_phpscoper_expose_class($exposed, $prefixed) {
        if (!class_exists($exposed, false) && !interface_exists($exposed, false) && !trait_exists($exposed, false)) {
            spl_autoload_call($prefixed);
        }
    }
}
humbug_phpscoper_expose_class('ComposerAutoloaderInitf30135b3d2cdb4ba5dcaea9dbdc98f9f', 'PopupKitScopedDependencies\ComposerAutoloaderInitf30135b3d2cdb4ba5dcaea9dbdc98f9f');
humbug_phpscoper_expose_class('ComposerAutoloaderInitdf2f968b85a9349cce2d05f822a26071', 'PopupKitScopedDependencies\ComposerAutoloaderInitdf2f968b85a9349cce2d05f822a26071');

// Function aliases. For more information see:
// https://github.com/humbug/php-scoper/blob/master/docs/further-reading.md#function-aliases
if (!function_exists('esc_attr')) { function esc_attr() { return \PopupKitScopedDependencies\esc_attr(...func_get_args()); } }

return $loader;
